### ISSUE TITLE
Cannot build anymore (nullptr can only be converted to pointer)

### ISSUE THREAD

**Issue by jochemstoel** [AtsushiSuzuki/node-clr#10]
Hi, I am unable to NPM install _clr_ and I don't understand why.  I tried it on different machines, each with Visual Studio 2015 and NPM package _windows-build-tools_ installed and configured.  

I receive several versions of the following error message:
*nullptr can only be converted to pointer or handle types*

```bash
D:\>npm i clr

> clr@0.0.18 install D:\node_modules\clr
> node-gyp rebuild


D:\node_modules\clr>if not defined npm_config_node_gyp (node "C:\bin\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  DllMain.cc
  node-clr.cc
  Marshal.cc
  CLRObject.cc
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\Marshal.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\Marshal.cc)
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\DllMain.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\DllMain.cc)
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\Marshal.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\Marshal.cc)
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\DllMain.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\DllMain.cc)
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\node-clr.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\node-clr.cc)
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\CLRObject.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\CLRObject.cc)
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\node-clr.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\node-clr.cc)
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\CLRObject.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\CLRObject.cc)
  CLRBinder.cc
  V8Function.cc
  V8Delegate.cc
  V8InvocationException.cc
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\CLRBinder.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\CLRBinder.cc)
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\V8Function.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\V8Function.cc)
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\CLRBinder.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\CLRBinder.cc)
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\V8Function.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\V8Function.cc)
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\V8Delegate.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\V8Delegate.cc)
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\V8Delegate.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\V8Delegate.cc)
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\V8InvocationException.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4080): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\V8InvocationException.cc)
C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): error C2664: 'std::pair<std::unique_ptr<const uint8_t [
],std::default_delete<_Ty>>,size_t>::pair(std::pair<std::unique_ptr<_Ty,std::default_delete<_Ty>>,size_t> &&)': cannot
convert argument 1 from 'nullptr' to 'nullptr &&' [D:\node_modules\clr\build\clr.vcxproj]
          with
          [
              _Ty=const uint8_t []
          ] (compiling source file ..\src\V8InvocationException.cc)
  C:\Users\Administrator\.node-gyp\8.4.0\include\node\v8.h(4081): note: nullptr can only be converted to pointer or han
  dle types (compiling source file ..\src\V8InvocationException.cc)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\bin\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\bin\\nodejs\\node.exe" "C:\\bin\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\node_modules\clr
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'D:\package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clr@0.0.18 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the clr@0.0.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-09-12T05_20_30_441Z-debug.log
``` 
This is weird because it used to build just fine on the same machine.

**Comment by AtsushiSuzuki** [comment]
I have two question:

- Did you installed other Visual Studio?
  - Maybe you are using wrong version of VC++ toolchain. try `npm config get msvs_version` and tell me what it says.
- Did you upgraded Node.js?
  - It's possible that newer version of node, v8 or gyp isn't compatible with VC++ 2015.

Anyways, I'll try to find out what happened, so please wait a while.

**Comment by jochemstoel** [comment]
I used _node-v8.4.0-x64_ and I did not install a different Visual Studio.

```bash
>npm config get msvs_version
2015
``` 
Your suggestion that this is related to the Node version is correct. Trying different versions of Node, I got it to work using _node-v7.0.0-x64_. 

## node-v6.11.3-x64

```bash
C:\Users\Administrator\Desktop\node_modules\clr>if not defined npm_config_node_gyp (node "C:\bin\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  node-clr.cc
  DllMain.cc
  Marshal.cc
  CLRObject.cc
..\src\CLRObject.cc(19): error C2039: 'ToChecked': is not a member of 'v8::Maybe<bool>' [C:\Users\Administrator\Desktop
\node_modules\clr\build\clr.vcxproj]
  CLRBinder.cc
  V8Function.cc
  V8Delegate.cc
  V8InvocationException.cc
```

Thank you for your quick response.

**Comment by AtsushiSuzuki** [comment]
Seems that the latest Node.js and V8 will not compile with MSVS 2015. (maybe since 8.0?)

If you install Visual Studio 2017 and it's C++, clr will build against Node.js 8.4.0.

**Comment by AtsushiSuzuki** [comment]
If you want to use latest Node.js runtime, try Build Tools for Visual Studio 2017 (https://www.visualstudio.com/en/downloads/) and `npm config set msvs_version 2017`.
